package fillshoppingcart;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.*;
import java.text.*;

/**
 *
 * @author Ashiq
 */
public class FillCart extends javax.swing.JFrame {

    /**
     * Creates new form FillCart
     */
   // FillCart.setIconImage(createImage("https://raw.githubusercontent.com/Md-Ashiqur-Rahaman-Nishad/Filling-Your-Shopping-Cart/master/shopping.png").getImage());
    
    DefaultTableModel model;
    DecimalFormat df = new DecimalFormat("#.##");

    public FillCart() {
        icon();
        initComponents();
        jPanel1.setVisible(false);
        WrongInput.setVisible(false);
        WrongInput1.setVisible(false);
        model = (DefaultTableModel) tblData.getModel();
    }
    
    private void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Shoppify-bd300.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cmbProdType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ProductQty = new javax.swing.JTextField();
        EnterProdInfo = new javax.swing.JButton();
        ErrorMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        WrongInput = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        WrongInput1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoppify BD");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(43, 174, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fillshoppingcart/Shoppify-bd_.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("INPUT PRODUCT INFO");

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Product Type");

        cmbProdType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select--]", "Divisible", "Undivisible" }));
        cmbProdType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbProdTypeMouseClicked(evt);
            }
        });
        cmbProdType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbProdTypeKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("How Many Products");

        ProductQty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductQty.setText("Avialable Product Qty");
        ProductQty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductQty.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        ProductQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductQtyMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductQtyMouseExited(evt);
            }
        });
        ProductQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductQtyActionPerformed(evt);
            }
        });
        ProductQty.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ProductQtyPropertyChange(evt);
            }
        });
        ProductQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProductQtyKeyPressed(evt);
            }
        });

        EnterProdInfo.setBackground(new java.awt.Color(43, 174, 102));
        EnterProdInfo.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        EnterProdInfo.setText("Enter");
        EnterProdInfo.setToolTipText("");
        EnterProdInfo.setBorder(null);
        EnterProdInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterProdInfoActionPerformed(evt);
            }
        });

        ErrorMessage.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(255, 51, 255));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "            Products", "          Item Taken"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        WrongInput.setBackground(new java.awt.Color(255, 255, 255));
        WrongInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 174, 102)));
        WrongInput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel42.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Profit will be maximum:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout WrongInputLayout = new javax.swing.GroupLayout(WrongInput);
        WrongInput.setLayout(WrongInputLayout);
        WrongInputLayout.setHorizontalGroup(
            WrongInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WrongInputLayout.setVerticalGroup(
            WrongInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WrongInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WrongInputLayout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        WrongInput1.setBackground(new java.awt.Color(255, 255, 255));
        WrongInput1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 174, 102)));
        WrongInput1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("By taking these items:");

        javax.swing.GroupLayout WrongInput1Layout = new javax.swing.GroupLayout(WrongInput1);
        WrongInput1.setLayout(WrongInput1Layout);
        WrongInput1Layout.setHorizontalGroup(
            WrongInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(61, 61, 61)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WrongInput1Layout.setVerticalGroup(
            WrongInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(43, 174, 102));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WrongInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbProdType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EnterProdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ErrorMessage)
                                        .addComponent(ProductQty, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WrongInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(ErrorMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterProdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WrongInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WrongInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProductQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductQtyMouseClicked
        // TODO add your handling code here

        jPanel1.setVisible(false);
        WrongInput.setVisible(false);
        WrongInput1.setVisible(false);
        model = (DefaultTableModel) tblData.getModel();

        String Temp = ProductQty.getText();
        if ("Avialable Product Qty".equals(Temp)) {
            ProductQty.setText(null);
        }
    }//GEN-LAST:event_ProductQtyMouseClicked

    private void ProductQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductQtyActionPerformed
        // TODO add your handling code here:
        //String PrevReadiing = LastReading.getText();
    }//GEN-LAST:event_ProductQtyActionPerformed

    private void ProductQtyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ProductQtyPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductQtyPropertyChange

    private void ProductQtyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductQtyMouseExited

    }//GEN-LAST:event_ProductQtyMouseExited

    public void knapsack(int n, double weight[], double profit[], double capacity) {
        double x[] = new double[100];
        double tp = 0, u;
        int i, j;
        u = capacity;

        for (i = 0; i < n; i++) {
            x[i] = 0.0;
        }

        for (i = 0; i < n; i++) {
            if (weight[i] > u) {
                break;
            } else {
                x[i] = 1.0;
                tp = tp + profit[i];
                u = u - weight[i];
            }
        }

        if (i < n) {
            x[i] = u / weight[i];
        }

        tp = tp + (x[i] * profit[i]);

        jLabel8.setText(String.valueOf(df.format(tp)));

        for (i = 0; i < n; i++) {

            String st = String.valueOf(df.format(x[i]*100));
            model.insertRow(tblData.getRowCount(), new Object[]{
                "Product " + String.valueOf(i + 1), st+"%"
            });

        }

        WrongInput.setVisible(true);
        WrongInput1.setVisible(true);
        jPanel1.setVisible(true);

    }

    int max(int a, int b) {
        return (a > b) ? a : b;
    }

    void printknapSack(int W, int wt[], int val[], int n) {

        int i, w;
        int K[][] = new int[n + 1][W + 1];

        for (i = 0; i <= n; i++) {
            for (w = 0; w <= W; w++) {
                if (i == 0 || w == 0) {
                    K[i][w] = 0;
                } else if (wt[i - 1] <= w) {
                    K[i][w] = Math.max(val[i - 1]
                            + K[i - 1][w - wt[i - 1]], K[i - 1][w]);
                } else {
                    K[i][w] = K[i - 1][w];
                }
            }
        }

        int res = K[n][W];
        jLabel8.setText(String.valueOf(df.format(res)));

        w = W;
        for (i = n; i > 0 && res > 0; i--) {
            if (res == K[i - 1][w]) {
                continue;
            } else {
                //System.out.print(wt[i - 1] + " product " + i + " ");
                String st = String.valueOf(df.format(i));
                model.insertRow(tblData.getRowCount(), new Object[]{
                    "Product " + st, "Total Item"
                });
                res = res - val[i - 1];
                w = w - wt[i - 1];
            }
        }
        WrongInput.setVisible(true);
        WrongInput1.setVisible(true);
        jPanel1.setVisible(true);
    }

    private void EnterProdInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterProdInfoActionPerformed
        model.setRowCount(0);

        if (cmbProdType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(FillCart.this, "Please select product type", "Invalid Product Type", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(ProductQty.getText()==null){
            JOptionPane.showMessageDialog(FillCart.this, "Please enter number of avialable products", "Invalid Product Qty", JOptionPane.ERROR_MESSAGE);
        }

        if (cmbProdType.getSelectedIndex() == 1) {
            //code for divisible input using "Fractional Knapsack Algorithm"//
            if (ProductQty.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(FillCart.this, "Please enter avialable number of product", "Invalid Product Qty", JOptionPane.ERROR_MESSAGE);
            }

            int productNumber = Integer.parseInt(ProductQty.getText().trim());

            double[] profit = new double[100];
            double[] weight = new double[100];
            double[] ratio = new double[100];
            double temp;
            int i, j;

            for (i = 0; i < productNumber; i++) {
               String s = JOptionPane.showInputDialog(FillCart.this, "Enter price for product " + (i + 1) + ": ", "Product Price", JOptionPane.QUESTION_MESSAGE);

                while (s.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(FillCart.this, "Please enter a valid number", "Invalid Attempt", JOptionPane.ERROR_MESSAGE);
                    s = JOptionPane.showInputDialog(FillCart.this, "Enter price for product " + (i + 1) + ": ", "Product Price", JOptionPane.QUESTION_MESSAGE);
                } 
                profit[i] = Double.parseDouble(s);
            }

            JOptionPane.showMessageDialog(FillCart.this, "Please enter weight of the products", "Proceed", JOptionPane.OK_OPTION);

            for (j = 0; j < productNumber; j++) {
                String s = JOptionPane.showInputDialog(FillCart.this, "Enter weight for product " + (j + 1) + ": ", "Product Weight", JOptionPane.QUESTION_MESSAGE);

                while (s.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(FillCart.this, "Please enter a valid number", "Invalid Attempt", JOptionPane.ERROR_MESSAGE);
                    s = JOptionPane.showInputDialog(FillCart.this, "Enter weight for product " + (j + 1) + ": ", "Product Weight", JOptionPane.QUESTION_MESSAGE);
                } 
                weight[j] = Double.parseDouble(s);
            }

            JOptionPane.showMessageDialog(FillCart.this, "Please enter capacity of the bag", "Proceed", JOptionPane.OK_OPTION);

            //double KnapsackCapacity = Double.parseDouble(JOptionPane.showInputDialog(FillCart.this, "Enter bag/cart capacity : ", "Knapsack Capacity", JOptionPane.QUESTION_MESSAGE));
            
            String s = JOptionPane.showInputDialog(FillCart.this, "Enter bag/cart capacity : ", "Knapsack Capacity", JOptionPane.QUESTION_MESSAGE);
            while (s.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(FillCart.this, "Please enter a valid number", "Invalid Attempt", JOptionPane.ERROR_MESSAGE);
                    s = JOptionPane.showInputDialog(FillCart.this, "Enter bag/cart capacity : ", "Knapsack Capacity", JOptionPane.QUESTION_MESSAGE);
                }
            
            double KnapsackCapacity = Double.parseDouble(s);

            for (i = 0; i < productNumber; i++) {
                ratio[i] = profit[i] / weight[i];
            }

            for (i = 0; i < productNumber; i++) {
                for (j = i + 1; j < productNumber; j++) {
                    if (ratio[i] < ratio[j]) {
                        temp = ratio[j];
                        ratio[j] = ratio[i];
                        ratio[i] = temp;

                        temp = weight[j];
                        weight[j] = weight[i];
                        weight[i] = temp;

                        temp = profit[j];
                        profit[j] = profit[i];
                        profit[i] = temp;
                    }
                }
            }

            knapsack(productNumber, weight, profit, KnapsackCapacity);
        } else if (cmbProdType.getSelectedIndex() == 2) {
            //code for divisible input using "0/1 Knapsack Algorithm"//
            if (ProductQty.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(FillCart.this, "Please enter avialable number of product", "Invalid Product Qty", JOptionPane.ERROR_MESSAGE);
            }

            int productNumber = Integer.parseInt(ProductQty.getText().trim());

            int[] profit = new int[100];
            int[] weight = new int[100];
            int i, j;

            for (i = 0; i < productNumber; i++) {

                String s = JOptionPane.showInputDialog(FillCart.this, "Enter price for product " + (i + 1) + ": ", "Product Price", JOptionPane.QUESTION_MESSAGE);

                while (s.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(FillCart.this, "Please enter a valid number", "Invalid Attempt", JOptionPane.ERROR_MESSAGE);
                    s = JOptionPane.showInputDialog(FillCart.this, "Enter price for product " + (i + 1) + ": ", "Product Price", JOptionPane.QUESTION_MESSAGE);
                } 
                profit[i] = Integer.parseInt(s);                    
   
            }

            JOptionPane.showMessageDialog(FillCart.this, "Please enter weight of the products", "Proceed", JOptionPane.OK_OPTION);

            for (j = 0; j < productNumber; j++) {
                String s = JOptionPane.showInputDialog(FillCart.this, "Enter weight for product " + (j + 1) + ": ", "Product Weight", JOptionPane.QUESTION_MESSAGE);

                while (s.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(FillCart.this, "Please enter a valid number", "Invalid Attempt", JOptionPane.ERROR_MESSAGE);
                    s = JOptionPane.showInputDialog(FillCart.this, "Enter weight for product " + (j + 1) + ": ", "Product Weight", JOptionPane.QUESTION_MESSAGE);
                } 
                weight[j] = Integer.parseInt(s);
            }

            JOptionPane.showMessageDialog(FillCart.this, "Please enter capacity of the bag", "Proceed", JOptionPane.OK_OPTION);

            //int KnapsackCapacity = Integer.parseInt(JOptionPane.showInputDialog(FillCart.this, "Enter bag/cart capacity : ", "Knapsack Capacity", JOptionPane.QUESTION_MESSAGE));
            
            String s = JOptionPane.showInputDialog(FillCart.this, "Enter bag/cart capacity : ", "Knapsack Capacity", JOptionPane.QUESTION_MESSAGE);
            while (s.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(FillCart.this, "Please enter a valid number", "Invalid Attempt", JOptionPane.ERROR_MESSAGE);
                    s = JOptionPane.showInputDialog(FillCart.this, "Enter bag/cart capacity : ", "Knapsack Capacity", JOptionPane.QUESTION_MESSAGE);
                }
            
            int KnapsackCapacity = Integer.parseInt(s);

            printknapSack(KnapsackCapacity, weight, profit, productNumber);

        }
    }//GEN-LAST:event_EnterProdInfoActionPerformed

    private void ProductQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductQtyKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (Character.isLetter(ch)) {
            ProductQty.setEditable(false);
            ErrorMessage.setText("Only Numbers!!");
        } else {
            ProductQty.setEditable(true);
        }
    }//GEN-LAST:event_ProductQtyKeyPressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        tblData.clearSelection();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void cmbProdTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbProdTypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProdTypeKeyPressed

    private void cmbProdTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProdTypeMouseClicked
        // TODO add your handling code here:
        WrongInput.setVisible(false);
        WrongInput1.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_cmbProdTypeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        cmbProdType.setSelectedItem("[--Select--]");
        ProductQty.setText("");
        WrongInput.setVisible(false);
        WrongInput1.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterProdInfo;
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JTextField ProductQty;
    private static javax.swing.JPanel WrongInput;
    private static javax.swing.JPanel WrongInput1;
    private javax.swing.JComboBox<String> cmbProdType;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
